In [20]:
import os
import pandas as pd

In [21]:
high_quality_cases = pd.read_csv('high_quality_cases.csv', index_col = 0)

In [22]:
trained_model_path = '/home/miguel/GI/1 - Segmentation/UNet-and-Synthesis-Results/TrainedModels'
trained_model_folders = os.listdir(trained_model_path)

In [23]:
case_ids = set(high_quality_cases['case_id'].unique())

In [24]:
existing_trained_models = set(os.listdir('TrainedModels'))

In [16]:
high_quality_cases[high_quality_cases['case_id'] == 'case148_day20']

Empty DataFrame
Columns: [case_id, mean_pixel_value, pixel_var, case_number, day_number]
Index: []

In [ ]:
high_quality_cases

           case_id  mean_pixel_value     pixel_var  case_number  day_number
188    case20_day0       1029.524259  3.032759e+06           20           0
186   case20_day22       1290.596892  3.984502e+06           20          22
187   case20_day24       1054.318013  3.012459e+06           20          24
230    case22_day0        657.101284  1.352360e+06           22           0
201    case24_day0       1131.384381  4.255613e+06           24           0
..             ...               ...           ...          ...         ...
113   case154_day0       1299.200388  4.166867e+06          154           0
116  case154_day13       1246.785161  3.895897e+06          154          13
115  case154_day14       1176.476026  3.585702e+06          154          14
112  case154_day16       1209.700527  3.711969e+06          154          16
114  case154_day17       1304.223785  4.257067e+06          154          17

[161 rows x 5 columns]

In [17]:
matching_folders = []   
for trained_model_folder in trained_model_folders:
    case_day = trained_model_folder.split('_slice')[0]
    if case_day in case_ids:
        if os.path.exists(os.path.join(trained_model_path, trained_model_folder, 'scale_factor=0.750000,alpha=10', 'Gs.pth')):
            if trained_model_folder not in existing_trained_models:
                matching_folders.append(trained_model_folder)

In [18]:
# Transfer to the trained models folder
import shutil
for folder in matching_folders:
    src = os.path.join(trained_model_path, folder)
    dst = os.path.join('TrainedModels', folder)
    shutil.copytree(src, dst)

In [19]:
matching_folders

[]

In [34]:
len(matching_folders)

97

In [35]:
len(trained_model_folders)

211